#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-licensed-business
  flyway:
    enabled: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
schedulers:
  update-assignment-status:
    name: updateAssignmentStatus
    cron: 0 0 1 * * *
    shedlock-lock-at-most-for: PT10M
    maximum-execution-time: PT10M
